default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :database) %>
  host: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :host) %>
  port: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :port) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :password) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
